### ISSUE TITLE
Keep the Android SDK optional under forthcoming Bazel versions

### ISSUE THREAD

**Issue by cpovirk** [google/bazel-common#114]
From https://github.com/bazelbuild/continuous-integration/issues/1006, I get the impression (but haven't confirmed) that forthcoming versions of Bazel are going to require that any registered Android toolchains are present, even if they're not used. Flogger (and probably Inject-Common and perhaps other projects?) don't use Android, so it would be nice for people who build them not to need to download one.

I'm not sure of the best way to do this, but maybe support `google_common_workspace_rules(android=False)` (or `android_version=None` if we want to allow projects to not just disable support but also change the version?)? I'm not sure if this would put us on a road to supporting a zillion configuration options.

**Comment by chaoren** [comment]
Obsolete with bzlmod. We can't set the Android SDK for the user even if we wanted to.
