### ISSUE TITLE
javadoc_library doesn't grok tree artifacts

### ISSUE THREAD

**Issue by ghost** [google/bazel-common#161]
I am trying to use generate Javadoc from auto-generated Java sources (e.g. Java bindings generated from WSDL). My Java source generator produces a tree artifact. However, I cannot provide tree artifacts to `javadoc_library`, because `javadoc_library` simply passes `srcs` directly to the `javadoc` command-line. As a result, the action fails with the following:

```
javadoc: error - Illegal package name: "bazel-out/k8-dbg-obj/bin/path/to/my/treeartifact
```

**Comment by netdpb** [comment]
What do you mean by a "tree artifact"?

**Comment by beasleyr-vmw** [comment]
> What do you mean by a "tree artifact"?

https://bazel.build/reference/glossary#artifact sums it up better than I could. :)

> A source file or a generated file. **Can also be a directory of files, known as "tree artifacts". Tree artifacts are black boxes to Bazel**: Bazel does not treat the files in tree artifacts as individual artifacts and thus cannot reference them directly as action inputs / outputs. An artifact can be an input to multiple actions, but must only be generated by at most one action.

**Comment by netdpb** [comment]
Aha. So since passing a directory to [`Args.add_all()`](https://bazel.build/rules/lib/Args#add_all) actually adds each file recursively found in that directory, we just switch to using `Args`?

**Comment by cpovirk** [comment]
I think this happened through some combination of https://github.com/google/bazel-common/pull/166 and https://github.com/google/bazel-common/commit/f11fc5a75eef2733518b11b2ca8de7e7a13c8f31. There may well still be things that don't work—I think I remember discussing source jars, for example—but this should at least be worth another look now if you're still interested.
