### ISSUE TITLE
Release a repository archive for consistent checksum

### ISSUE THREAD

**Issue by l46kok** [google/bazel-common#167]
Per https://github.com/bazel-contrib/SIG-rules-authors/issues/11, the checksum of repository code download archives (https://github.com/google/bazel-common/archive/_COMMIT_.zip) are not stable.

In fact, the checksum was changed earlier today as seen in the above issue, though that change was rolled back. Please consider releasing an archive under `/archive/refs/tags/$tag`, which its SHA256 value is promised to be stable.

**Comment by chaoren** [comment]
Maybe we should just use `git_repository` instead of `http_archive` in the README? We don't currently do fixed [releases](https://github.com/google/bazel-common/releases) here, so I'm not sure want to start promising them.

**Comment by l46kok** [comment]
`git_repository` is unideal in many circumstances, since it doesn't support repository caching and it requires downstream users to have git installed (especially problematic for CI / docker container builds). [The Bazel team also recommends against using `git_repository`](https://bazel.build/docs/external#best-practices).

**Comment by chaoren** [comment]
Obsolete as we've migrated to bzlmod and are using `git_override` with a commit hash instead.

> unideal in many circumstances, since it doesn't support repository caching and it requires downstream users to have git installed

These points might still be relevant, but this repository exists for our own benefit and we're not running into any of those issues.
