### ISSUE TITLE
jarjar_library def fails on bazel 0.19.1

### ISSUE THREAD

**Issue by perezd** [google/bazel-common#37]
version:
Build label: 0.19.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Nov 12 15:32:30 2018 (1542036750)
Build timestamp: 1542036750
Build timestamp as int: 1542036750

It complains this label no longer exists: `@local_jdk//:jdk-default`. I think there's a different one we should be using here instead.

**Comment by ronshapiro** [comment]
Fixed in https://github.com/google/bazel-common/commit/55049dacf10255c91a934797ca2f1310066f0d38 and will be out in tomorrow's sync. Thanks for reporting!
