### ISSUE TITLE
Protobuf should be updated to 3.7.0

### ISSUE THREAD

**Issue by perezd** [google/bazel-common#51]
Turns out there are more bazel deprecations:
https://github.com/protocolbuffers/protobuf/issues/5547

One thing I noticed is the maven jar is 3.6.1 (released july) and 3.6.1.3 (released december) doesn't have a protobuf_java corollary. I asked them to cut one but I assume that would block adoption here?

**Comment by perezd** [comment]
Current workaround for a .bazelrc:
```
build --incompatible_package_name_is_a_function=false
```

**Comment by ronshapiro** [comment]
I've also been waiting for that. But I just checked the diff, and I'm not seeing much that actually changed functionally, and I think I'd be willing to upgrade the bazel rules on their own unless they're comfortable making a Maven release soon

**Comment by perezd** [comment]
Yeah I pinged the thread, let's see what they say.

**Comment by perezd** [comment]
OK so with Bazel 0.22 released officially this is now a fatal error. Codebase no longer compiles and the workaround flag is gone. What should we do?

**Comment by Reflexe** [comment]
Someone was too happy to deprecate that. For now, we could compile the binaries by ourselves (like with grpc-java) instead of using maven's.

**Comment by perezd** [comment]
Any update here?

**Comment by perezd** [comment]
https://search.maven.org/artifact/com.google.protobuf/protobuf-java/3.7.0/bundle

3.7.0 is now available @ Maven which has this patch.

**Comment by perezd** [comment]
I'm taking a stab at this upgrade but its blocked by the bug referenced above.
