### ISSUE TITLE
checker_framework_annotations only exports compatqual

### ISSUE THREAD

**Issue by perezd** [google/bazel-common#56]
So annotations only exports:
```
"@org_checkerframework_checker_compat_qual//jar",
```

It should probably also expose:
```
 "@org_checkerframework_checker_qual//jar",
```

compat_qual doesn't have what I would expect like Nullable etc.

**Comment by ronshapiro** [comment]
While likely to be surprising, this is a relic of Google's internal repo and kept for consistency.
