### ISSUE TITLE
javadoc_library not finding sources

### ISSUE THREAD

**Issue by deadmoose** [google/bazel-common#58]
`javadoc.bzl` builds its list of sourcepaths via `find * [stuff]`:

https://github.com/google/bazel-common/blob/master/tools/javadoc/javadoc.bzl#L37

The execroot it's sitting in is chock full of symlinks to the concrete workspace, and that find won't follow them, so the javadoc invocation fails complaining `javadoc: error - No public or protected classes found to document.`

If I hack that to use either a `-L` or to glob `*/`, it _does_ find them, but it's blindly crawling my whole source tree and gives javadoc for my test classes.

I'm seeing the same behavior trying to build javadoc for flogger, so I'm pretty sure I'm holding it right, but I tossed together a pretty bare bones demo repository to confirm: https://github.com/deadmoose/javadoctest

**Comment by ronshapiro** [comment]
There aren't actually any sources in your example. the recursive glob is returning empty because both `src/main/java/com/deadmoose/{foo,bar}` both have BUILD files.

**Comment by ronshapiro** [comment]
I will make sure to make it required for `srcs` to be non-empty so that we catch this at the right place.
